MATH_KEYWORDS = [
    "vector", "вектор",
    "matrix", "матрица",
    "eigenvalue", "eigenvector",
    "собственное значение", "собственный вектор",
    "norm", "норма",
    "gradient", "градиент",
    "jacobian", "якобиан",
    "hessian", "гессиан",
    "integral", "интеграл",
    "orthogonal", "ортогональный",
    "span", "подпространство",
    "pca"
]
ML_KEYWORDS = [
    "overfitting", "переобучение",
    "underfitting", "недообучение",
    "bias-variance", "bias variance",
    "loss function", "loss",
    "regularization", "регуляризация",
    "gradient descent", "sgd",
    "epoch", "batch",
    "hyperparameter", "гиперпараметр",
    "cross-validation", "кросс-валидация",
    "inference",
]
OPS_KEYWORDS = [
    "docker",
    "dockerfile",
    "container",
    "kubernetes",
    "k8s",
    "helm",
    "ci/cd",
    "deployment",
    "orchestration",
    "mlops",
    "devops",
    "image registry",
]
PYTHON_KEYWORDS = [
    "decorator", "декоратор",
    "generator", "генератор",
    "yield",
    "async", "await",
    "list comprehension",
    "dict comprehension",
    "lambda",
    "pip",
    "virtualenv", "venv",
    "import",
]
STAT_KEYWORDS = [
    "probability", "вероятность",
    "bayes", "байес",
    "random variable", "случайная величина",
    "distribution", "распределение",
    "normal distribution",
    "binomial distribution",
    "expectation", "мат ожидание",
    "variance", "дисперсия",
    "standard deviation",
    "law of large numbers",
    "central limit theorem",
]
SOFTSKILLS_KEYWORDS = [
    "communication", "коммуникация",
    "feedback", "обратная связь",
    "teamwork", "работа в команде",
    "leadership", "лидерство",
    "conflict", "конфликт",
    "motivation", "мотивация",
    "empathy", "эмпатия",
]
